### ISSUE TITLE
Correct category

### ISSUE THREAD

**Issue by caxton** [siddharthachandra/DavisToCoco#2]
Hi @siddharthachandra , thanks for this tool. Is there any way to get correct category and convert it to COCO category? Thanks.

**Comment by siddharthachandra** [comment]
Hi Caxton. Unfortunately we do not have category labels in the DAVIS dataset. Further, DAVIS is an instance tracking dataset, therefore not all instances for each class are annotated. Even if you manually label the annotated instances, you will have to be careful so as to not use the unannotated instances as negatives for training your classifier.

**Comment by siddharthachandra** [comment]
Hi Caxton. Unfortunately we do not have category labels in the DAVIS dataset. Further, DAVIS is an instance tracking dataset, therefore not all instances for each class are annotated. Even if you manually label the annotated instances, you will have to be careful so as to not use the unannotated instances as negatives for training your classifier.
